Cloning into '/home/timothy/.texttest/tmp/texttest.19Mar162658.1117/texttest/list/List-available-from-invalid-URI/.subuser/repositories/default'...
Repository id: file://invalid-uri could not be resolved.
